### ISSUE TITLE
Adding a CONTRIBUTING file

### ISSUE THREAD

**Issue by bhdicaire** [Arudjreis/awesome-security-GRC#5]
Hello,

I would like to propose a guidelines for repository contributors based on the [GITHUB guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors).

For an example of a `contribute` page, see [github/docs/contribute](https://github.com/github/docs/contribute).

**Comment by Arudjreis** [comment]
Great idea, I think it should really help.

The tone, layout of the page as well as the coverage depth level should be laid out somewhere.

I kind of know how it should be like but something needs a more formal guideline document.
